### ISSUE TITLE
Error thrown when executing tests

### ISSUE THREAD

**Issue by sebastian-zarzycki-es** [ui-router/react#37]
```
class Application extends Component {
    render() {
        return (
            <UIRouter plugins={[pushStateLocationPlugin]} config={this.onRouterInitialized}>
                    <UIView />
            </UIRouter>
        )
    }

    onRouterInitialized(router) {
	    let stateDefinitions = [
	        {
	            name: 'home',
	            url: '/home',
	            component: Home
	        }
	    ];

	    router.urlRouter.when('/', '/home');
	    router.urlRouter.otherwise('/error/not-found');
	    stateDefinitions.forEach(state => router.stateRegistry.register(state));
    }
}
```

The application works fine in browser, but when executing a simple test:

```
it('renders without crashing', () => {
  const div = document.createElement('div');
  ReactDOM.render(<Application />, div);
});
```
the test itself passes, but complains with
```
console.error node_modules/ui-router-core/lib/state/stateService.js:35
    TypeError: Cannot read property 'getElementsByTagName' of undefined
        at BrowserLocationConfig.Object.<anonymous>.BrowserLocationConfig.applyDocumentBaseHref (/Users/rattkin/Documents/Workspaces/WebStorm/project/node_modules/ui-router-core/lib/vanilla/browserLocationConfig.js:36:32)
        at BrowserLocationConfig.Object.<anonymous>.BrowserLocationConfig.baseHref (/Users/rattkin/Documents/Workspaces/WebStorm/project/node_modules/ui-router-core/lib/vanilla/browserLocationConfig.js:33:94)
        at UrlRouter.Object.<anonymous>.UrlRouter.href (/Users/rattkin/Documents/Workspaces/WebStorm/project/node_modules/ui-router-core/lib/url/urlRouter.js:186:66)

  console.error node_modules/ui-router-core/lib/state/stateService.js:36
    TypeError: Cannot read property 'getElementsByTagName' of undefined
        at BrowserLocationConfig.Object.<anonymous>.BrowserLocationConfig.applyDocumentBaseHref (/Users/rattkin/Documents/Workspaces/WebStorm/project/node_modules/ui-router-core/lib/vanilla/browserLocationConfig.js:36:32)
        at BrowserLocationConfig.Object.<anonymous>.BrowserLocationConfig.baseHref (/Users/rattkin/Documents/Workspaces/WebStorm/project/node_modules/ui-router-core/lib/vanilla/browserLocationConfig.js:33:94)
        at UrlRouter.Object.<anonymous>.UrlRouter.href (/Users/rattkin/Documents/Workspaces/WebStorm/project/node_modules/ui-router-core/lib/url/urlRouter.js:186:66)
```

I'm testing using the standard "npm test" from react-create-app.

Seems like there is an issue with providing base href. Since I'm testing component and not whole index (where the base usually is), it has a problem.

**Comment by elboman** [comment]
I think the problem is due to the test environment. The sample code uses `pushStateLocationPlugin` which is probably not implemented in the test env you're using.

When testing with the router, you may want to use the `memoryLocationPlugin` which doesn't rely on any native browser api and simply keeps the url in memory.
