### ISSUE TITLE
Jest/Enzyme Transition Rejection/TypeError

### ISSUE THREAD

**Issue by hthomann** [ui-router/react#735]
HI!  In our react app we are using UIRouter.  I'm adding our first Enzyme test.  All I did was install Enzyme, create the necessary Enzyme adapter, and added a very bare bones test of a very simple component in our out.  The test passes successfully.  However, 
in the test output I see the following from UIRouter:

console.error node_modules/@uirouter/core/lib/state/stateService.js:37
    Transition Rejection($id: 1 type: 6, message: The transition errored, detail: TypeError: Cannot read property 'body' of null)

  console.error node_modules/@uirouter/core/lib/state/stateService.js:39
    TypeError: Cannot read property 'body' of null
        at getActiveElement (E:\gitSource\myApp\node_modules\react-dom\cjs\react-dom.development.js:6651:16)
        at getActiveElementDeep (E:\gitSource\myApp\node_modules\react-dom\cjs\react-dom.development.js:6939:17)
        at getSelectionInformation (E:\gitSource\myApp\node_modules\react-dom\cjs\react-dom.development.js:6972:21)
        at prepareForCommit (E:\gitSource\myApp\node_modules\react-dom\cjs\react-dom.development.js:7463:26)
        at commitRootImpl (E:\gitSource\myApp\node_modules\react-dom\cjs\react-dom.development.js:22474:5)
        at unstable_runWithPriority (E:\gitSource\myApp\node_modules\scheduler\cjs\scheduler.development.js:653:12)
        at runWithPriority$1 (E:\gitSource\myApp\node_modules\react-dom\cjs\react-dom.development.js:11039:10)
        at commitRoot (E:\gitSource\myApp\node_modules\react-dom\cjs\react-dom.development.js:22381:3)
        at finishSyncRender (E:\gitSource\myApp\node_modules\react-dom\cjs\react-dom.development.js:21807:3)
        at performSyncWorkOnRoot (E:\gitSource\myApp\node_modules\react-dom\cjs\react-dom.development.js:21793:7)
        at E:\gitSource\myApp\node_modules\react-dom\cjs\react-dom.development.js:11089:24
        at unstable_runWithPriority (E:\gitSource\myApp\node_modules\scheduler\cjs\scheduler.development.js:653:12)
        at runWithPriority$1 (E:\gitSource\myApp\node_modules\react-dom\cjs\react-dom.development.js:11039:10)
        at flushSyncCallbackQueueImpl (E:\gitSource\myApp\node_modules\react-dom\cjs\react-dom.development.js:11084:7)
        at flushSyncCallbackQueue (E:\gitSource\myApp\node_modules\react-dom\cjs\react-dom.development.js:11072:3)
        at scheduleUpdateOnFiber (E:\gitSource\myApp\node_modules\react-dom\cjs\react-dom.development.js:21199:9)
        at Object.enqueueSetState (E:\gitSource\myApp\node_modules\react-dom\cjs\react-dom.development.js:12639:5)
        at View.Object.<anonymous>.Component.setState (E:\gitSource\myApp\node_modules\react\cjs\react.development.js:471:16)
        at View.Object.<anonymous>.View.viewConfigUpdated (E:\gitSource\myApp\node_modules\@uirouter\react\lib\components\@uirouter\react\components\UIView.tsx:249:10)
        at configureUIView (E:\gitSource\myApp\node_modules\@uirouter\core\lib\view\@uirouter\core\view\view.ts:265:68)
        at Array.forEach (<anonymous>)
        at ViewService.Object.<anonymous>.ViewService.sync (E:\gitSource\myApp\node_modules\@uirouter\core\lib\view\@uirouter\core\view\view.ts:275:18)
        at activateViews (E:\gitSource\myApp\node_modules\@uirouter\core\lib\hooks\@uirouter\core\hooks\views.ts:48:9)
        at invokeCallback (E:\gitSource\myApp\node_modules\@uirouter\core\lib\transition\@uirouter\core\transition\transitionHook.ts:143:48)
        at TransitionHook.Object.<anonymous>.TransitionHook.invokeHook (E:\gitSource\myApp\node_modules\@uirouter\core\lib\transition\@uirouter\core\transition\transitionHook.ts:152:22)
        at E:\gitSource\myApp\node_modules\@uirouter\core\lib\transition\@uirouter\core\transition\transitionHook.ts:114:32
        at Array.forEach (<anonymous>)
        at Object.<anonymous>.TransitionHook.runAllHooks (E:\gitSource\myApp\node_modules\@uirouter\core\lib\transition\@uirouter\core\transition\transitionHook.ts:114:11)
        at transitionSuccess (E:\gitSource\myApp\node_modules\@uirouter\core\lib\transition\@uirouter\core\transition\transition.ts:782:7)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)

Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total

**Comment by christopherthielen** [comment]
Sounds like you're running into this: https://github.com/facebook/react/issues/15691
This is caused when async callbacks tell react to render a component after the test is torn down.  Make sure your async tests are properly written.

```
it('async test', async () => {
  var wrapper = mount(<UIView/>);
  await someAsyncThing();
})
```

I'm not an expert on on react async testing, but you'll likely need to wrap some operations in [act](https://reactjs.org/docs/test-utils.html#act).  I believe you may also need to wrap async operations in async act, 

```
await act(async () => {
  asyncAction()
});
```

Finally, you can try to unmount your component at the end of your test:
```
wrapper.unmount()
```
